### ISSUE TITLE
[Bug]: Omada won't start on raspberrypi 5

### ISSUE THREAD

**Issue by KevinEdry** [mbentley/docker-omada-controller#447] opened 2024-07-19 00:57 UTC
### Controller Version

v5.14
also tried on v5.14-arm64

### Describe the Bug

When starting docker via this image, Omada encounters an error and exits.

### Expected Behavior

The docker should run and should expose the 8088 and 8043 ports for the portal.

### Steps to Reproduce

Run the CLI below in a raspberry pi 5 on a raspberry pi os lite 64bit.

### How You're Launching the Container

```plain
docker run -d \
  --name omada-controller \
  --stop-timeout 60 \
  --restart unless-stopped \
  --ulimit nofile=4096:8192 \
  -p 8088:8088 \
  -p 8043:8043 \
  -p 8843:8843 \
  -p 27001:27001/udp \
  -p 29810:29810/udp \
  -p 29811-29816:29811-29816 \
  -e MANAGE_HTTP_PORT=8088 \
  -e MANAGE_HTTPS_PORT=8043 \
  -e PGID="508" \
  -e PORTAL_HTTP_PORT=8088 \
  -e PORTAL_HTTPS_PORT=8843 \
  -e PORT_ADOPT_V1=29812 \
  -e PORT_APP_DISCOVERY=27001 \
  -e PORT_DISCOVERY=29810 \
  -e SKIP_USERLAND_KERNEL_CHECK=true \
  -e PORT_MANAGER_V1=29811 \
  -e PORT_MANAGER_V2=29814 \
  -e PORT_TRANSFER_V2=29815 \
  -e PORT_RTTY=29816 \
  -e PORT_UPGRADE_V1=29813 \
  -e PUID="508" \
  -e SHOW_SERVER_LOGS=true \
  -e SHOW_MONGODB_LOGS=false \
  -e SSL_CERT_NAME="tls.crt" \
  -e SSL_KEY_NAME="tls.key" \
  -e TZ=Etc/UTC \
  -v /DATA/AppData/omada/data:/opt/tplink/EAPController/data \
  -v /DATA/AppData/omada/logs:/opt/tplink/EAPController/logs \
  mbentley/omada-controller:5.14-arm64
```

### Container Logs

```plain
[server.log](https://github.com/user-attachments/files/16298820/server.log)
```

### MongoDB Logs

```plain
[mongod.log](https://github.com/user-attachments/files/16299082/mongod.log)
```

### Additional Context

The 8043 isn't being used, I don't know why it can't attach to it.
```bash
pi@raspberrypi:~ $ sudo ss -ltnp
State  Recv-Q Send-Q Local Address:Port    Peer Address:Port Process                                     
LISTEN 0      4096       127.0.0.1:46799        0.0.0.0:*     users:(("casaos",pid=873,fd=9))            
LISTEN 0      4096       127.0.0.1:33873        0.0.0.0:*     users:(("casaos-message-",pid=850,fd=7))   
LISTEN 0      50           0.0.0.0:139          0.0.0.0:*     users:(("smbd",pid=1001,fd=31))            
LISTEN 0      4096       127.0.0.1:41687        0.0.0.0:*     users:(("casaos-user-ser",pid=883,fd=7))   
LISTEN 0      128          0.0.0.0:22           0.0.0.0:*     users:(("sshd",pid=818,fd=3))              
LISTEN 0      50           0.0.0.0:445          0.0.0.0:*     users:(("smbd",pid=1001,fd=30))            
LISTEN 0      4096       127.0.0.1:45463        0.0.0.0:*     users:(("casaos-app-mana",pid=1798,fd=10)) 
LISTEN 0      4096       127.0.0.1:36175        0.0.0.0:*     users:(("casaos-local-st",pid=907,fd=9))   
LISTEN 0      4096         0.0.0.0:8080         0.0.0.0:*     users:(("docker-proxy",pid=57324,fd=4))    
LISTEN 0      4096       127.0.0.1:39437        0.0.0.0:*     users:(("casaos-gateway",pid=831,fd=11))   
LISTEN 0      4096       127.0.0.1:35635        0.0.0.0:*     users:(("casaos-gateway",pid=831,fd=3))    
LISTEN 0      511        127.0.0.1:39029        0.0.0.0:*     users:(("homebridge: hom",pid=2311,fd=33)) 
LISTEN 0      511                *:46339              *:*     users:(("homebridge: hom",pid=2311,fd=21)) 
LISTEN 0      50              [::]:139             [::]:*     users:(("smbd",pid=1001,fd=29))            
LISTEN 0      4096               *:80                 *:*     users:(("casaos-gateway",pid=831,fd=8))    
LISTEN 0      128             [::]:22              [::]:*     users:(("sshd",pid=818,fd=4))              
LISTEN 0      50              [::]:445             [::]:*     users:(("smbd",pid=1001,fd=28))            
LISTEN 0      511                *:8581               *:*     users:(("hb-service",pid=2177,fd=21))      
LISTEN 0      4096            [::]:8080            [::]:*     users:(("docker-proxy",pid=57332,fd=4))    
LISTEN 0      511                *:51720              *:*     users:(("homebridge",pid=2299,fd=23))   
```

**Comment by mbentley** [comment] 2024-07-19 00:59
Duplicate of #418; [see this post](https://github.com/mbentley/docker-omada-controller/issues/418#issuecomment-2223732459) for instructions on rolling back to 5.13

**Closed by mbentley** 2024-07-19 00:59 UTC
