### ISSUE TITLE
[Bug]: Docker Build 32cdad2e3888 is broken

### ISSUE THREAD

**Issue by ARLBR10** [mbentley/docker-omada-controller#449] opened 2024-07-19 04:00 UTC
### Controller Version

Docker 5.13 (Stable) -> Docker 5.14 (Stable)

### Describe the Bug

The build looks like its broken because running on a preloaded environment and new environment gives errors while startup that make it unable to work.

### Expected Behavior

Wait to sucessfully logs and panel to show

### Steps to Reproduce

(PRE-MADE INVIROMENT)
1. edit the docker-compose.yml
2. go to the line `image: mbentley/omada-controller:5.13` and edit '5.13' to '5.14'
3. delete the previous container (optional)
4. use 'docker compose up -d' 

(NEW ENVIROMENT)
1. download the docker-compose.yml
2. use 'docker compose up -d' 

### How You're Launching the Container

```plain
I am using 'docker compose' with a macvlan to create an own container lan ip

Worked fine in 5.13 

docker-compose.yml (Version 5.13)

version: "3.1"

services:
  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:5.13
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    networks:
      homemacvlan:
        ipv4_address: 192.168.250.2
    environment:
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=80
      - MANAGE_HTTPS_PORT=443
      - PORTAL_HTTP_PORT=80
      - PORTAL_HTTPS_PORT=443
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=Etc/UTC
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs

volumes:
  omada-data:
    external: true
  omada-logs:
    external: true

networks:
  homemacvlan:
    external: true
```

### Container Logs

```plain
(logs at omada-logs volume from new enviroment)
https://pastebin.com/40pUvD55
```

### MongoDB Logs

```plain
(logs at omada-logs volume from new enviroment)
2024-07-19T03:34:26.745+0000 I CONTROL  [initandlisten] MongoDB starting : pid=212 port=27217 dbpath=../data/db 64-bit host=7afd2b721b2a
2024-07-19T03:34:26.746+0000 I CONTROL  [initandlisten] db version v3.6.8
2024-07-19T03:34:26.746+0000 I CONTROL  [initandlisten] git version: 8e540c0b6db93ce994cc548f000900bdc740f80a
2024-07-19T03:34:26.746+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
2024-07-19T03:34:26.746+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2024-07-19T03:34:26.746+0000 I CONTROL  [initandlisten] modules: none
2024-07-19T03:34:26.746+0000 I CONTROL  [initandlisten] build environment:
2024-07-19T03:34:26.746+0000 I CONTROL  [initandlisten]     distarch: x86_64
2024-07-19T03:34:26.746+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2024-07-19T03:34:26.746+0000 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 27217 }, processManagement: { pidFilePath: "../data/mongo.pid" }, storage: { dbPath: "../data/db" }, systemLog: { destination: "file", logAppend: true, path: "../logs/mongod.log" } }
2024-07-19T03:34:26.746+0000 I STORAGE  [initandlisten] 
2024-07-19T03:34:26.746+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2024-07-19T03:34:26.746+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2024-07-19T03:34:26.746+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7433M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),cache_cursors=false,compatibility=(release="3.0",require_max="3.0"),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2024-07-19T03:34:27.381+0000 I STORAGE  [initandlisten] WiredTiger message [1721360067:381355][212:0x74111309bac0], txn-recover: Set global recovery timestamp: 0
2024-07-19T03:34:27.414+0000 I CONTROL  [initandlisten] 
2024-07-19T03:34:27.414+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2024-07-19T03:34:27.414+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2024-07-19T03:34:27.414+0000 I CONTROL  [initandlisten] 
2024-07-19T03:34:27.414+0000 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: 699e8160-212e-4092-a589-b46d19ff3ebd
2024-07-19T03:34:27.430+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.6
2024-07-19T03:34:27.434+0000 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 16280d18-167f-46ab-aeae-8a2db5210500
2024-07-19T03:34:27.448+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '../data/db/diagnostic.data'
2024-07-19T03:34:27.449+0000 I STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with generated UUID: e57b632c-1b47-4261-b754-a0e8fbee9481
2024-07-19T03:34:27.449+0000 I NETWORK  [initandlisten] waiting for connections on port 27217
2024-07-19T03:34:27.470+0000 I INDEX    [LogicalSessionCacheRefresh] build index on: config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 }
2024-07-19T03:34:27.470+0000 I INDEX    [LogicalSessionCacheRefresh] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2024-07-19T03:34:27.472+0000 I INDEX    [LogicalSessionCacheRefresh] build index done.  scanned 0 total records. 0 secs
2024-07-19T03:34:28.987+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:46814 #1 (1 connection now open)
2024-07-19T03:34:28.987+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:46818 #2 (2 connections now open)
2024-07-19T03:34:29.003+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:46814 conn1: { driver: { name: "mongo-java-driver|sync", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:34:29.003+0000 I NETWORK  [conn2] received client metadata from 127.0.0.1:46818 conn2: { driver: { name: "mongo-java-driver|sync", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:34:29.129+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:46828 #3 (3 connections now open)
2024-07-19T03:34:29.130+0000 I NETWORK  [conn3] received client metadata from 127.0.0.1:46828 conn3: { driver: { name: "mongo-java-driver|sync", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:34:29.167+0000 I NETWORK  [conn3] end connection 127.0.0.1:46828 (2 connections now open)
2024-07-19T03:34:29.168+0000 I NETWORK  [conn2] end connection 127.0.0.1:46818 (1 connection now open)
2024-07-19T03:34:29.168+0000 I NETWORK  [conn1] end connection 127.0.0.1:46814 (0 connections now open)
2024-07-19T03:34:47.956+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:51926 #4 (1 connection now open)
2024-07-19T03:34:47.957+0000 I NETWORK  [conn4] received client metadata from 127.0.0.1:51926 conn4: { driver: { name: "mongo-java-driver|sync|spring-boot", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:34:47.958+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:51942 #5 (2 connections now open)
2024-07-19T03:34:47.960+0000 I NETWORK  [conn5] received client metadata from 127.0.0.1:51942 conn5: { driver: { name: "mongo-java-driver|sync|spring-boot", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:34:48.458+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:51948 #6 (3 connections now open)
2024-07-19T03:34:48.459+0000 I NETWORK  [conn6] received client metadata from 127.0.0.1:51948 conn6: { driver: { name: "mongo-java-driver|sync", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:34:48.470+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:51960 #7 (4 connections now open)
2024-07-19T03:34:48.471+0000 I NETWORK  [conn7] received client metadata from 127.0.0.1:51960 conn7: { driver: { name: "mongo-java-driver|sync", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:34:48.477+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:51974 #8 (5 connections now open)
2024-07-19T03:34:48.477+0000 I NETWORK  [conn8] received client metadata from 127.0.0.1:51974 conn8: { driver: { name: "mongo-java-driver|sync", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:34:48.486+0000 I NETWORK  [conn6] end connection 127.0.0.1:51948 (4 connections now open)
2024-07-19T03:34:48.487+0000 I NETWORK  [conn8] end connection 127.0.0.1:51974 (3 connections now open)
2024-07-19T03:34:48.487+0000 I NETWORK  [conn7] end connection 127.0.0.1:51960 (2 connections now open)
2024-07-19T03:34:51.442+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:51984 #9 (3 connections now open)
2024-07-19T03:34:51.443+0000 I NETWORK  [conn9] received client metadata from 127.0.0.1:51984 conn9: { driver: { name: "mongo-java-driver|sync|spring-boot", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:34:51.470+0000 I STORAGE  [conn9] createCollection: omada.schedulecentertask with generated UUID: 40b7e2d6-6c0b-43af-8bdb-1089bfd9d02c
2024-07-19T03:34:51.903+0000 I NETWORK  [conn9] end connection 127.0.0.1:51984 (2 connections now open)
2024-07-19T03:34:51.904+0000 I NETWORK  [conn4] end connection 127.0.0.1:51926 (1 connection now open)
2024-07-19T03:34:51.904+0000 I NETWORK  [conn5] end connection 127.0.0.1:51942 (0 connections now open)
2024-07-19T03:34:59.175+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:33986 #10 (1 connection now open)
2024-07-19T03:34:59.177+0000 I NETWORK  [conn10] received client metadata from 127.0.0.1:33986 conn10: { driver: { name: "mongo-java-driver|sync|spring-boot", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:34:59.183+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:33988 #11 (2 connections now open)
2024-07-19T03:34:59.185+0000 I NETWORK  [conn11] received client metadata from 127.0.0.1:33988 conn11: { driver: { name: "mongo-java-driver|sync|spring-boot", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:34:59.231+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:33996 #12 (3 connections now open)
2024-07-19T03:34:59.232+0000 I NETWORK  [conn12] received client metadata from 127.0.0.1:33996 conn12: { driver: { name: "mongo-java-driver|sync", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:34:59.235+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:34002 #13 (4 connections now open)
2024-07-19T03:34:59.235+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:34004 #14 (5 connections now open)
2024-07-19T03:34:59.236+0000 I NETWORK  [conn13] received client metadata from 127.0.0.1:34002 conn13: { driver: { name: "mongo-java-driver|sync", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:34:59.236+0000 I NETWORK  [conn14] received client metadata from 127.0.0.1:34004 conn14: { driver: { name: "mongo-java-driver|sync", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:34:59.243+0000 I NETWORK  [conn14] end connection 127.0.0.1:34004 (4 connections now open)
2024-07-19T03:34:59.243+0000 I NETWORK  [conn12] end connection 127.0.0.1:33996 (3 connections now open)
2024-07-19T03:34:59.244+0000 I NETWORK  [conn13] end connection 127.0.0.1:34002 (2 connections now open)
2024-07-19T03:35:00.464+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:34018 #15 (3 connections now open)
2024-07-19T03:35:00.465+0000 I NETWORK  [conn15] received client metadata from 127.0.0.1:34018 conn15: { driver: { name: "mongo-java-driver|sync|spring-boot", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:35:00.756+0000 I NETWORK  [conn15] end connection 127.0.0.1:34018 (2 connections now open)
2024-07-19T03:35:00.756+0000 I NETWORK  [conn10] end connection 127.0.0.1:33986 (1 connection now open)
2024-07-19T03:35:00.756+0000 I NETWORK  [conn11] end connection 127.0.0.1:33988 (0 connections now open)
2024-07-19T03:35:00.800+0000 I CONTROL  [signalProcessingThread] got signal 15 (Terminated), will terminate after current cmd ends
2024-07-19T03:35:00.800+0000 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2024-07-19T03:35:00.800+0000 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27217.sock
2024-07-19T03:35:00.801+0000 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2024-07-19T03:35:00.803+0000 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2024-07-19T03:35:00.871+0000 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2024-07-19T03:35:00.871+0000 I CONTROL  [signalProcessingThread] now exiting
2024-07-19T03:35:00.871+0000 I CONTROL  [signalProcessingThread] shutting down with code:0
2024-07-19T03:35:10.148+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
2024-07-19T03:35:10.154+0000 I CONTROL  [initandlisten] MongoDB starting : pid=186 port=27217 dbpath=../data/db 64-bit host=7afd2b721b2a
2024-07-19T03:35:10.154+0000 I CONTROL  [initandlisten] db version v3.6.8
2024-07-19T03:35:10.154+0000 I CONTROL  [initandlisten] git version: 8e540c0b6db93ce994cc548f000900bdc740f80a
2024-07-19T03:35:10.154+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
2024-07-19T03:35:10.154+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2024-07-19T03:35:10.154+0000 I CONTROL  [initandlisten] modules: none
2024-07-19T03:35:10.154+0000 I CONTROL  [initandlisten] build environment:
2024-07-19T03:35:10.154+0000 I CONTROL  [initandlisten]     distarch: x86_64
2024-07-19T03:35:10.154+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2024-07-19T03:35:10.154+0000 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 27217 }, processManagement: { pidFilePath: "../data/mongo.pid" }, storage: { dbPath: "../data/db" }, systemLog: { destination: "file", logAppend: true, path: "../logs/mongod.log" } }
2024-07-19T03:35:10.155+0000 I -        [initandlisten] Detected data files in ../data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2024-07-19T03:35:10.155+0000 I STORAGE  [initandlisten] 
2024-07-19T03:35:10.155+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2024-07-19T03:35:10.155+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2024-07-19T03:35:10.155+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7433M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),cache_cursors=false,compatibility=(release="3.0",require_max="3.0"),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2024-07-19T03:35:10.935+0000 I STORAGE  [initandlisten] WiredTiger message [1721360110:935949][186:0x70730fa76ac0], txn-recover: Main recovery loop: starting at 1/24832
2024-07-19T03:35:11.041+0000 I STORAGE  [initandlisten] WiredTiger message [1721360111:41427][186:0x70730fa76ac0], txn-recover: Recovering log 1 through 2
2024-07-19T03:35:11.102+0000 I STORAGE  [initandlisten] WiredTiger message [1721360111:102553][186:0x70730fa76ac0], txn-recover: Recovering log 2 through 2
2024-07-19T03:35:11.148+0000 I STORAGE  [initandlisten] WiredTiger message [1721360111:148513][186:0x70730fa76ac0], txn-recover: Set global recovery timestamp: 0
2024-07-19T03:35:11.174+0000 I CONTROL  [initandlisten] 
2024-07-19T03:35:11.174+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2024-07-19T03:35:11.174+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2024-07-19T03:35:11.174+0000 I CONTROL  [initandlisten] 
2024-07-19T03:35:11.189+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '../data/db/diagnostic.data'
2024-07-19T03:35:11.189+0000 I NETWORK  [initandlisten] waiting for connections on port 27217
2024-07-19T03:35:12.158+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:36512 #1 (1 connection now open)
2024-07-19T03:35:12.158+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:36510 #2 (2 connections now open)
2024-07-19T03:35:12.170+0000 I NETWORK  [conn2] received client metadata from 127.0.0.1:36510 conn2: { driver: { name: "mongo-java-driver|sync", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:35:12.171+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:36512 conn1: { driver: { name: "mongo-java-driver|sync", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:35:12.242+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:36524 #3 (3 connections now open)
2024-07-19T03:35:12.243+0000 I NETWORK  [conn3] received client metadata from 127.0.0.1:36524 conn3: { driver: { name: "mongo-java-driver|sync", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:35:12.270+0000 I NETWORK  [conn3] end connection 127.0.0.1:36524 (2 connections now open)
2024-07-19T03:35:12.271+0000 I NETWORK  [conn1] end connection 127.0.0.1:36512 (1 connection now open)
2024-07-19T03:35:12.271+0000 I NETWORK  [conn2] end connection 127.0.0.1:36510 (0 connections now open)
2024-07-19T03:35:12.318+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:36534 #4 (1 connection now open)
2024-07-19T03:35:12.318+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:36532 #5 (2 connections now open)
2024-07-19T03:35:12.319+0000 I NETWORK  [conn4] received client metadata from 127.0.0.1:36534 conn4: { driver: { name: "mongo-java-driver|sync", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:35:12.319+0000 I NETWORK  [conn5] received client metadata from 127.0.0.1:36532 conn5: { driver: { name: "mongo-java-driver|sync", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:35:12.323+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:36544 #6 (3 connections now open)
2024-07-19T03:35:12.324+0000 I NETWORK  [conn6] received client metadata from 127.0.0.1:36544 conn6: { driver: { name: "mongo-java-driver|sync", version: "4.6.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.5.0-44-generic" }, platform: "Java/Ubuntu/17.0.11+9-Ubuntu-120.04.2" }
2024-07-19T03:35:12.330+0000 I NETWORK  [conn6] end connection 127.0.0.1:36544 (2 connections now open)
2024-07-19T03:35:12.330+0000 I NETWORK  [conn4] end connection 127.0.0.1:36534 (1 connection now open)
2024-07-19T03:35:12.330+0000 I NETWORK  [conn5] end connection 127.0.0.1:36532 (0 connections now open)
```

**Comment by ARLBR10** [comment] 2024-07-19 04:01
I forgot to mention that this is the latest version at the moment and i was just trying to update and found an "error" if its applicable

**Comment by mbentley** [comment] 2024-07-19 10:14
Duplicate of #418; [see this post](https://github.com/mbentley/docker-omada-controller/issues/418#issuecomment-2223732459) for instructions on rolling back to 5.13

**Closed by mbentley** 2024-07-19 10:14 UTC
